"""Export representable native sample instruments as SFZ text."""

import json
import math

from .. import base, envelope, modulation
from ..assets import RelativeFileLocation
from ..control import Clock, Scope
from ..samples import controls, crossfade, enums, playback, processing, selection
from ..samples.instrument import (
    SampleInstrumentScore,
    SampleSlot,
    effective_selection,
    effective_settings,
)
from ..streams import AudioType
from .model import (
    InstrumentLocation,
    Opcode,
    SfzExportResult,
    UnimplementedFeature,
    _channel_routes,
)


def write(instrument: SampleInstrumentScore) -> SfzExportResult:
    """Serialize a native instrument without reading or writing sample assets."""
    issues: list[UnimplementedFeature] = []
    _instrument_issues(instrument, issues)
    groups = _choke_groups(instrument)
    regions: list[list[str]] = []
    slot_groups = {g.name: g for g in instrument.body.groups}
    for i, slot in enumerate(instrument.body.slots):
        group = slot_groups.get(slot.group)
        if group is not None:
            slot = SampleSlot.model_validate(
                slot.model_dump()
                | effective_settings(slot, group).model_dump()
                | {'group': None, 'selection': effective_selection(slot, group)}
            )
        opcodes = _region(instrument, slot, i, groups, issues)
        if opcodes is None:
            continue
        metadata = '// recs:slot ' + _json(
            {
                'name': slot.name,
                'title': slot.title,
                'description': slot.description,
                'tags': slot.tags,
            }
        )
        regions.append(
            [metadata, '<region>', *(f'{o.name}={o.value}' for o in opcodes)]
        )
    if not regions:
        _issue(
            issues,
            'body.slots',
            instrument.body.slots,
            'No slot can be represented as an SFZ region',
        )
        return SfzExportResult(contents='// Generated by Ufor\n', unimplemented=issues)
    lines = [
        '// Generated by Ufor',
        '// recs:instrument '
        + _json(
            {
                'version': 2,
                'title': instrument.title,
                'description': instrument.description,
                'tags': instrument.tags,
            }
        ),
    ]
    for region in regions:
        lines.extend(['', *region])
    return SfzExportResult(contents='\n'.join(lines) + '\n', unimplemented=issues)


def _instrument_issues(
    document: SampleInstrumentScore, issues: list[UnimplementedFeature]
) -> None:
    instrument = document.body.settings
    if instrument.voice_policy is not None:
        _issue(
            issues,
            'body.settings.voice_policy',
            instrument.voice_policy,
            'Voice policy has no exact SFZ conversion',
        )
    for i, parameter in enumerate(document.parameters):
        _issue(
            issues,
            f'parameters[{i}]',
            parameter,
            'Public parameter exports have no SFZ conversion',
        )
    if instrument.selections:
        for i, value in enumerate(instrument.selections):
            _issue(
                issues,
                f'body.settings.selections[{i}]',
                value,
                'SFZ alternate-selection behavior is not represented',
            )
    if instrument.articulations is not None:
        _issue(
            issues,
            'body.settings.articulations',
            instrument.articulations,
            'Instrument articulation declarations require an external input binding',
        )
    canonical_sustain = selection.Sustain(control='sustain')
    canonical_controls = {'sustain': controls.ControlDeclaration()}
    if instrument.sustain != canonical_sustain:
        _issue(
            issues,
            'body.settings.sustain',
            instrument.sustain,
            'SFZ only provides its implicit canonical sustain-pedal behavior',
        )
    if instrument.controls != canonical_controls:
        _issue(
            issues,
            'body.settings.controls',
            instrument.controls,
            'Named instrument controls require an external SFZ input binding',
        )
    _sound_issues(instrument, 'body.settings', issues)


def _sound_issues(
    settings: processing.SoundSettings,
    path: str,
    issues: list[UnimplementedFeature],
) -> None:
    for i, value in enumerate(settings.processing.filters):
        _issue(
            issues,
            f'{path}.processing.filters[{i}]',
            value,
            'Resonant filters have no implemented SFZ conversion',
        )
    for i, value in enumerate(settings.processing.equalizer):
        _issue(
            issues,
            f'{path}.processing.equalizer[{i}]',
            value,
            'Instrument equalizer bands have no implemented SFZ conversion',
        )
    for name, value in settings.motions.items():
        _issue(
            issues,
            f'{path}.motions.{name}',
            value,
            'Instrument motions have no implemented SFZ conversion',
        )
    for i, value in enumerate(settings.modulation.routes):
        _issue(
            issues,
            f'{path}.modulation.routes[{i}]',
            value,
            'Instrument-wide modulation has no exact SFZ region conversion',
        )


def _region(
    document: SampleInstrumentScore,
    slot: SampleSlot,
    index: int,
    groups: dict[str, int],
    issues: list[UnimplementedFeature],
) -> list[Opcode] | None:
    path = f'body.slots[{index}]'
    sample_slice = next(s for s in document.body.slices if s.name == slot.slice)
    asset = next(a for a in document.assets if a.name == sample_slice.asset)
    if not isinstance(asset.location, RelativeFileLocation):
        _issue(
            issues,
            f'{path}.sample',
            asset.location,
            'SFZ export requires a relative-file sample location',
        )
        return None
    sample = asset.location.path
    try:
        expected_channels = _channel_routes(
            len(asset.audio.channels),
            next(
                p.stream.channels
                for p in document.outputs
                if isinstance(p.stream, AudioType)
            ),
        )
    except ValueError:
        expected_channels = []
    if slot.channels != expected_channels:
        _issue(
            issues,
            f'{path}.channels',
            slot.channels,
            'Custom channel routing has no SFZ conversion',
        )
    sample_safe = _safe_sample(sample)
    if not sample_safe:
        _issue(
            issues,
            f'{path}.sample',
            sample,
            'Sample reference contains syntax that is unsafe in portable SFZ',
        )
    mapping_eligible = _mapping_eligible(slot.mapping, path, issues)
    if not sample_safe or not mapping_eligible:
        _diagnose_omitted_slot(document, slot, path, groups, issues)
        return None

    opcodes = [Opcode(name='sample', value=sample)]
    if slot.title is not None and _safe_value(slot.title):
        opcodes.insert(0, Opcode(name='region_label', value=slot.title))
    opcodes.extend(_mapping(slot.mapping))
    if slot.sequence is not None:
        if slot.sequence.length > 100:
            _issue(
                issues,
                f'{path}.sequence',
                slot.sequence,
                'SFZ sequence length must not exceed 100',
            )
        else:
            opcodes.extend(
                [
                    Opcode(name='seq_length', value=str(slot.sequence.length)),
                    Opcode(name='seq_position', value=str(slot.sequence.position)),
                ]
            )
            _issue(
                issues,
                f'{path}.sequence',
                slot.sequence,
                'SFZ players do not share one sequence counter rule',
            )
    opcodes.extend(_random_range_opcodes(slot.random_range))
    opcodes.extend(_trigger_opcodes(slot, path, issues))
    opcodes.extend(_choking(slot, path, groups, issues))
    opcodes.extend(_playback_opcodes(document, slot, path, issues))
    opcodes.extend(_processing_opcodes(document, slot, path, issues))
    opcodes.extend(_envelope_opcodes(document, slot, path, issues))
    opcodes.extend(_crossfade_opcodes(slot, path, issues))
    opcodes.extend(_modulation_opcodes(slot, path, issues))
    _slot_issues(slot, path, issues)
    return opcodes


def _diagnose_omitted_slot(
    document: SampleInstrumentScore,
    slot: SampleSlot,
    path: str,
    groups: dict[str, int],
    issues: list[UnimplementedFeature],
) -> None:
    _trigger_opcodes(slot, path, issues)
    _choking(slot, path, groups, issues)
    _playback_opcodes(document, slot, path, issues)
    instrument = document.body.settings.processing
    local = slot.processing
    if not slot.mapping.pitch_tracking and slot.mapping.reference_pitch_hz is not None:
        _issue(
            issues,
            f'{path}.mapping.reference_pitch_hz',
            slot.mapping.reference_pitch_hz,
            'An untracked SFZ region cannot retain a reference pitch as metadata',
        )
    if (instrument.pan + local.pan) and (
        instrument.stereo_balance + local.stereo_balance
    ):
        _issue(
            issues,
            f'{path}.processing',
            local,
            'One SFZ pan opcode cannot distinguish simultaneous pan and balance',
        )
    for i, band in enumerate(local.equalizer):
        _issue(
            issues,
            f'{path}.processing.equalizer[{i}]',
            band,
            'Instrument equalizer bands have no implemented SFZ conversion',
        )
    _envelope_opcodes(document, slot, path, issues)
    _crossfade_opcodes(slot, path, issues)
    _modulation_opcodes(slot, path, issues)
    _slot_issues(slot, path, issues)


def _mapping_eligible(
    mapping: playback.Mapping, path: str, issues: list[UnimplementedFeature]
) -> bool:
    valid = True
    if not 0 <= mapping.lowest_key <= mapping.highest_key <= 127:
        _issue(
            issues,
            f'{path}.mapping',
            mapping,
            'SFZ key bounds must be within 0 through 127',
        )
        valid = False
    for field in ('minimum_velocity', 'maximum_velocity'):
        value = getattr(mapping, field)
        if _velocity_number(value) is None:
            _issue(
                issues,
                f'{path}.mapping.{field}',
                value,
                'SFZ velocity bounds must be exact integer multiples of 1/127',
            )
            valid = False
    if mapping.event_key is not None:
        _issue(
            issues,
            f'{path}.mapping.event_key',
            mapping.event_key,
            'SFZ sustain event-key mappings require an external input binding',
        )
        valid = False
    if mapping.pitch_tracking and _pitch_key(mapping.reference_pitch_hz) is None:
        _issue(
            issues,
            f'{path}.mapping.reference_pitch_hz',
            mapping.reference_pitch_hz,
            'Reference pitch has no in-range SFZ pitch key center',
        )
        valid = False
    return valid


def _mapping(mapping: playback.Mapping) -> list[Opcode]:
    result = [
        Opcode(name='lokey', value=str(mapping.lowest_key)),
        Opcode(name='hikey', value=str(mapping.highest_key)),
        Opcode(name='lovel', value=str(_velocity_number(mapping.minimum_velocity))),
        Opcode(name='hivel', value=str(_velocity_number(mapping.maximum_velocity))),
    ]
    if mapping.pitch_tracking:
        assert mapping.reference_pitch_hz is not None
        assert (key := _pitch_key(mapping.reference_pitch_hz)) is not None
        result.append(Opcode(name='pitch_keycenter', value=str(key)))
    else:
        result.append(Opcode(name='pitch_keytrack', value='0'))
    return result


def _random_range_opcodes(value: selection.RandomRange | None) -> list[Opcode]:
    if value is None:
        return []
    return [
        Opcode(name='lorand', value=str(value.minimum)),
        Opcode(name='hirand', value=str(value.maximum)),
    ]


def _trigger_opcodes(
    slot: SampleSlot, path: str, issues: list[UnimplementedFeature]
) -> list[Opcode]:
    values = {
        enums.TriggerKind.start: None,
        enums.TriggerKind.release: 'release_key',
        enums.TriggerKind.logical_release: 'release',
    }
    if slot.trigger in values:
        value = values[slot.trigger]
        return [Opcode(name='trigger', value=value)] if value else []
    _issue(
        issues,
        f'{path}.trigger',
        slot.trigger,
        'Sustain-transition triggers require an external SFZ input binding',
    )
    return []


def _choke_groups(document: SampleInstrumentScore) -> dict[str, int]:
    groups: dict[str, int] = {}
    for slot in document.body.slots:
        if slot.choke_group is not None and slot.choke_group not in groups:
            groups[slot.choke_group] = len(groups) + 1
    return groups


def _choking(
    slot: SampleSlot,
    path: str,
    groups: dict[str, int],
    issues: list[UnimplementedFeature],
) -> list[Opcode]:
    result: list[Opcode] = []
    if slot.choke_group is not None:
        result.append(Opcode(name='group', value=str(groups[slot.choke_group])))
    if len(slot.chokes) > 1:
        for i, choke in enumerate(slot.chokes[1:], 1):
            _issue(
                issues,
                f'{path}.chokes[{i}]',
                choke,
                'An SFZ region can target only one choke group',
            )
    if not slot.chokes:
        return result
    choke = slot.chokes[0]
    if choke.mode == enums.ChokeMode.fade:
        _issue(
            issues,
            f'{path}.chokes[0]',
            choke,
            'Timed instrument fade choking has no exact SFZ off_mode',
        )
        return result
    result.extend(
        [
            Opcode(name='off_by', value=str(groups[choke.group])),
            Opcode(
                name='off_mode',
                value='fast' if choke.mode == enums.ChokeMode.immediate else 'normal',
            ),
        ]
    )
    return result


def _playback_opcodes(
    document: SampleInstrumentScore,
    slot: SampleSlot,
    path: str,
    issues: list[UnimplementedFeature],
) -> list[Opcode]:
    instrument = document.body.settings.playback
    value = slot.playback
    sample_slice = next(s for s in document.body.slices if s.name == slot.slice)
    direction = value.direction if value.direction is not None else instrument.direction
    direction_path = (
        f'{path}.playback.direction'
        if value.direction is not None
        else 'body.settings.playback.direction'
    )
    mode = value.mode if value.mode is not None else instrument.mode
    result: list[Opcode] = []
    if direction == enums.Direction.backward:
        result.append(Opcode(name='direction', value='reverse'))
    elif direction == enums.Direction.mirror:
        _issue(
            issues,
            direction_path,
            direction,
            'Mirror traversal has no exact SFZ direction',
        )
    if sample_slice.start_frame:
        result.append(Opcode(name='offset', value=str(sample_slice.start_frame)))
    if sample_slice.end_frame is not None:
        result.append(
            Opcode(name='end', value=str(_inclusive_end(sample_slice.end_frame)))
        )
    if sample_slice.loop is not None:
        loop = sample_slice.loop
        result.extend(
            [
                Opcode(
                    name='loop_mode',
                    value=(
                        'loop_continuous'
                        if loop.mode == enums.LoopMode.through_release
                        else 'loop_sustain'
                    ),
                ),
                Opcode(name='loop_start', value=str(loop.start_frame)),
                Opcode(name='loop_end', value=str(_inclusive_end(loop.end_frame))),
            ]
        )
        if loop.repeat_count is not None:
            result.append(Opcode(name='loop_count', value=str(loop.repeat_count)))
        if loop.crossfade_frames:
            _issue(
                issues,
                f'{path}.playback.loop.crossfade_frames',
                loop.crossfade_frames,
                'Loop crossfade frames have no exact implemented SFZ conversion',
            )
    else:
        result.append(
            Opcode(
                name='loop_mode',
                value='one_shot' if mode == enums.PlaybackMode.one_shot else 'no_loop',
            )
        )
    if value.play_count is not None:
        if value.play_count > 2**32:
            _issue(
                issues,
                f'{path}.playback.play_count',
                value.play_count,
                'SFZ count exceeds its supported range',
            )
        else:
            result.append(Opcode(name='count', value=str(value.play_count)))
    return result


def _processing_opcodes(
    document: SampleInstrumentScore,
    slot: SampleSlot,
    path: str,
    issues: list[UnimplementedFeature],
) -> list[Opcode]:
    instrument = document.body.settings.processing
    local = slot.processing
    volume = instrument.volume_db + local.volume_db
    tuning = instrument.tuning_cents + local.tuning_cents
    if slot.mapping.pitch_tracking:
        assert slot.mapping.reference_pitch_hz is not None
        assert (key := _pitch_key(slot.mapping.reference_pitch_hz)) is not None
        reference = 440.0 * 2 ** ((key - 69) / 12)
        tuning += 1200 * math.log2(slot.mapping.reference_pitch_hz / reference)
    elif slot.mapping.reference_pitch_hz is not None:
        _issue(
            issues,
            f'{path}.mapping.reference_pitch_hz',
            slot.mapping.reference_pitch_hz,
            'An untracked SFZ region cannot retain a reference pitch as metadata',
        )
    result: list[Opcode] = []
    if volume:
        result.append(Opcode(name='volume', value=_number_text(volume)))
    if tuning:
        transpose = round(tuning / 100)
        if not -127 <= transpose <= 127:
            _issue(
                issues,
                f'{path}.processing.tuning_cents',
                tuning,
                'Combined tuning exceeds SFZ transpose range',
            )
        else:
            residual = tuning - 100 * transpose
            if transpose:
                result.append(Opcode(name='transpose', value=str(transpose)))
            if residual:
                result.append(Opcode(name='tune', value=_number_text(residual)))
    pan = instrument.pan + local.pan
    balance = instrument.stereo_balance + local.stereo_balance
    if pan and balance:
        _issue(
            issues,
            f'{path}.processing',
            {'pan': pan, 'stereo_balance': balance},
            'One SFZ pan opcode cannot distinguish simultaneous pan and balance',
        )
    elif pan or balance:
        result.append(Opcode(name='pan', value=_number_text(100 * (pan or balance))))
    for i, band in enumerate(local.equalizer):
        _issue(
            issues,
            f'{path}.processing.equalizer[{i}]',
            band,
            'Instrument equalizer bands have no implemented SFZ conversion',
        )
    return result


def _envelope_opcodes(
    document: SampleInstrumentScore,
    slot: SampleSlot,
    path: str,
    issues: list[UnimplementedFeature],
) -> list[Opcode]:
    value = slot.envelope or document.body.settings.envelope
    envelope_path = (
        f'{path}.envelope' if slot.envelope is not None else 'body.settings.envelope'
    )
    segments = value.segments
    representable = (
        value.clock == Clock.seconds
        and value.scope == Scope.voice
        and value.initial == 0
        and value.hold
        and value.retrigger == envelope.Retrigger.current
        and len(segments) == 4
        and len(value.release) == 1
    )
    if representable:
        representable = (
            [s.to for s in segments[:3]] == [0, 1, 1]
            and [s.curve for s in segments] == [0, 0, 0, -5]
            and value.release[0].to == 0
            and value.release[0].curve == -5
        )
    if not representable:
        _issue(
            issues,
            envelope_path,
            value,
            'SFZ requires a seconds-based delay/attack/hold/decay envelope '
            'with linear attack and exponential decay/release',
        )
        return []
    values = dict(
        zip(
            ('ampeg_delay', 'ampeg_attack', 'ampeg_hold', 'ampeg_decay'),
            (float(s.duration) for s in segments),
            strict=True,
        )
    )
    values['ampeg_sustain'] = segments[-1].to * 100
    values['ampeg_release'] = float(value.release[0].duration)
    return [Opcode(name=n, value=_number_text(v)) for n, v in values.items()]


def _modulation_opcodes(
    slot: SampleSlot, path: str, issues: list[UnimplementedFeature]
) -> list[Opcode]:
    supported: list[modulation.Route] = []
    for i, curve in enumerate(slot.modulation.routes):
        if (
            curve.target == modulation.Target(name='processing', parameter='amplitude')
            and any(
                b.name == curve.source and b.kind == 'velocity' for b in slot.bindings
            )
            and curve.operation == modulation.Operation.multiply
            and curve.interpolation == modulation.Interpolation.linear
            and all(_velocity_number(p.input) is not None for p in curve.points)
            and all(0 <= p.amount <= 1 for p in curve.points)
        ):
            supported.append(curve)
        else:
            _issue(
                issues,
                f'{path}.modulation.routes[{i}]',
                curve,
                'Only linear amplitude-by-velocity modulation maps exactly to SFZ',
            )
    if len(supported) > 1:
        for curve in supported:
            _issue(
                issues,
                f'{path}.modulation',
                curve,
                'Multiple amplitude curves cannot share one SFZ amp_veltrack',
            )
        return [Opcode(name='amp_veltrack', value='0')]
    if not supported:
        return [Opcode(name='amp_veltrack', value='0')]
    result = [Opcode(name='amp_veltrack', value='100')]
    for point in supported[0].points:
        velocity = _velocity_number(point.input)
        assert velocity is not None
        result.append(
            Opcode(name=f'amp_velcurve_{velocity}', value=_number_text(point.amount))
        )
    return result


def _crossfade_opcodes(
    slot: SampleSlot, path: str, issues: list[UnimplementedFeature]
) -> list[Opcode]:
    result: list[Opcode] = []
    curves: dict[enums.CrossfadeInput, enums.FadeCurve] = {}
    for i, fade in enumerate(slot.crossfades):
        if not isinstance(fade, crossfade.KeyCrossfade):
            _issue(
                issues,
                f'{path}.crossfades[{i}]',
                fade,
                'Control crossfades require an external SFZ input binding',
            )
            continue
        if fade.input == enums.CrossfadeInput.velocity:
            start = _velocity_number(fade.start)
            end = _velocity_number(fade.end)
            if start is None or end is None:
                _issue(
                    issues,
                    f'{path}.crossfades[{i}]',
                    fade,
                    'SFZ velocity crossfades require integer multiples of 1/127',
                )
                continue
            suffix = 'vel'
        else:
            start, end, suffix = fade.start, fade.end, 'key'
        if fade.input in curves and curves[fade.input] != fade.curve:
            _issue(
                issues,
                f'{path}.crossfades[{i}].curve',
                fade.curve,
                'SFZ permits only one crossfade curve per input in a region',
            )
            continue
        curves[fade.input] = fade.curve
        prefix = 'xfin' if fade.direction == enums.FadeDirection.fade_in else 'xfout'
        result.extend(
            [
                Opcode(name=f'{prefix}_lo{suffix}', value=str(start)),
                Opcode(name=f'{prefix}_hi{suffix}', value=str(end)),
            ]
        )
    for source, curve in curves.items():
        suffix = 'key' if source == enums.CrossfadeInput.key else 'vel'
        result.append(
            Opcode(
                name=f'xf_{suffix}curve',
                value='gain' if curve == enums.FadeCurve.linear else 'power',
            )
        )
    return result


def _slot_issues(
    slot: SampleSlot, path: str, issues: list[UnimplementedFeature]
) -> None:
    for name in ('take', 'microphone', 'alignment_frames'):
        if value := getattr(slot, name):
            _issue(
                issues,
                f'{path}.{name}',
                value,
                'Linked microphone takes have no exact SFZ conversion',
            )
    for name, value in slot.variation.model_dump().items():
        if value:
            _issue(
                issues,
                f'{path}.variation.{name}',
                value,
                'Seeded variation has no exact SFZ conversion',
            )
    for i, value in enumerate(slot.processing.filters):
        _issue(
            issues,
            f'{path}.processing.filters[{i}]',
            value,
            'Resonant filters have no implemented SFZ conversion',
        )
    if slot.selection:
        _issue(
            issues,
            f'{path}.selection',
            slot.selection,
            'SFZ alternate-selection behavior is not represented',
        )
    for i, articulation in enumerate(slot.articulations):
        _issue(
            issues,
            f'{path}.articulations[{i}]',
            articulation,
            'Instrument articulations require an external SFZ input binding',
        )
    for name, value in slot.motions.items():
        _issue(
            issues,
            f'{path}.motions.{name}',
            value,
            'Instrument motions have no implemented SFZ conversion',
        )


def _pitch_key(value: float | None) -> int | None:
    if value is None:
        return None
    key = round(69 + 12 * math.log2(value / 440))
    return key if 0 <= key <= 127 else None


def _velocity_number(value: object) -> int | None:
    if not isinstance(value, (int, float)) or isinstance(value, bool):
        return None
    scaled = value * 127
    rounded = round(scaled)
    return rounded if math.isclose(scaled, rounded, rel_tol=0, abs_tol=1e-12) else None


def _inclusive_end(value: int) -> int:
    return value - 1


def _number_text(value: object) -> str:
    assert isinstance(value, (int, float)) and not isinstance(value, bool)
    number = float(value)
    if number == 0:
        return '0'
    if number.is_integer():
        return str(int(number))
    return repr(number)


def _safe_sample(value: str) -> bool:
    return _safe_value(value) and not value.startswith('*')


def _safe_value(value: str) -> bool:
    return not any(token in value for token in ('\n', '\r', '//', '/*', '<', '=', '#'))


def _issue(
    issues: list[UnimplementedFeature], path: str, value: object, reason: str
) -> None:
    issue = UnimplementedFeature(
        location=InstrumentLocation(path=path),
        value=_json_value(value),
        reason=reason,
    )
    if issue not in issues:
        issues.append(issue)


def _json(value: object) -> str:
    return json.dumps(
        value,
        ensure_ascii=False,
        separators=(',', ':'),
        default=_json_default,
    )


def _json_default(value: object) -> object:
    if isinstance(value, base.Model):
        return value.model_dump(mode='json')
    raise TypeError(f'Cannot serialize {type(value).__name__} as JSON')


def _json_value(value: object) -> str | None:
    if value is None:
        return None
    if isinstance(value, base.Model):
        return value.model_dump_json(exclude_none=False)
    return _json(value)
